export {TShirts} from 'pages/catalog/badminton/MensClothing/T-shirts'
export {News} from 'pages/news'
export {Home} from 'pages/home'
export {NotFoundPage} from 'pages/notFoundPage'
export {ClubProgramPage} from 'pages/clubProgramPage'